#datasources:
#  default:
#    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    schema-generate: CREATE
#    dialect: H2
#jpa:
#  default:
#    entity-scan:
#      packages:
#        - 'com.micronaut.app.todo'
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        show_sql: true
#        bytecode:
#          provider: none
#        connection:
#          db-type: h2